// A10 — Review Queue page.
// Shows pending report drafts generated by A10 for analyst approval.
// Route: /dashboard/review-queue

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { EmailDraftCard, type EmailDraft } from "@/components/agents/EmailDraftCard";
import {
  FileText,
  CheckCircle,
  XCircle,
  Edit3,
  Loader2,
  ChevronDown,
  ChevronUp,
  PlayCircle,
  Clock,
  AlertCircle,
  ShieldCheck,
  ShieldAlert,
  FlaskConical,
  Mail,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useDomain } from "@/hooks/use-domain";
import { cn } from "@/lib/utils";

interface ReportDraft {
  id: string;
  tenantId: string;
  reportType: string | null;
  weekNumber: number | null;
  status: string;
  pdfUrl: string | null;
  analystNotes: string | null;
  createdAt: string | null;
  approvedAt: string | null;
  content?: {
    executiveSummary?: string[];
    trafficSnapshot?: { sessions: number; users: number; conversions: number; engagedSessions: number };
    searchSnapshot?: { clicks: number; impressions: number; ctr: number; avgPosition: number };
    anomaliesSection?: { count: number; p0Count: number; p1Count: number; summary?: string };
    recommendationsSection?: { count: number };
    appendix?: { weekNumber: number; generatedAt: string; sourceRunIds: string[] };
    qaResults?: {
      passed: boolean;
      issues: string[];
      checkResults?: {
        factualConsistency: { passed: boolean; issues: string[] };
        completeness: { passed: boolean; issues: string[] };
        tone: { passed: boolean; issues: string[] };
      };
    };
  };
}

const STATUS_META: Record<string, { label: string; className: string }> = {
  draft: { label: "Draft", className: "border-transparent bg-muted text-muted-foreground" },
  pending_analyst: { label: "Pending Review", className: "border-transparent bg-amber-500/15 text-amber-400" },
  qa_review: { label: "QA Review", className: "border-transparent bg-blue-500/15 text-blue-400" },
  approved: { label: "Approved", className: "border-transparent bg-green-500/15 text-green-400" },
  delivered: { label: "Delivered", className: "border-transparent bg-cyan-500/15 text-cyan-400" },
  rejected: { label: "Rejected", className: "border-transparent bg-red-500/15 text-red-400" },
  qa_failed: { label: "QA Failed", className: "border-transparent bg-red-500/15 text-red-400" },
};

interface QAResponse {
  ok: boolean;
  passed: boolean;
  status: string;
  issues: string[];
  checkResults?: {
    factualConsistency: { passed: boolean; issues: string[] };
    completeness: { passed: boolean; issues: string[] };
    tone: { passed: boolean; issues: string[] };
  };
}

function ReportDraftCard({ draft }: { draft: ReportDraft }) {
  const { toast } = useToast();
  const qc = useQueryClient();
  const [expanded, setExpanded] = useState(false);
  const [editingNotes, setEditingNotes] = useState(false);
  const [notes, setNotes] = useState(draft.analystNotes ?? "");
  const [qaRunning, setQaRunning] = useState(false);
  const [qaResult, setQaResult] = useState<QAResponse | null>(
    // Pre-populate from content if QA was already run
    draft.content?.qaResults
      ? { ok: true, passed: draft.content.qaResults.passed, status: draft.status, issues: draft.content.qaResults.issues, checkResults: draft.content.qaResults.checkResults }
      : null,
  );
  const [emailRunning, setEmailRunning] = useState(false);

  const { data: emailDrafts = [] } = useQuery<EmailDraft[]>({
    queryKey: ["/api/agents/communication", draft.id],
    queryFn: async () => {
      const res = await fetch(`/api/agents/communication?tenantId=${encodeURIComponent(draft.tenantId)}&reportDraftId=${encodeURIComponent(draft.id)}`);
      if (!res.ok) return [];
      return res.json();
    },
  });

  const statusMeta = STATUS_META[draft.status] ?? STATUS_META.pending_analyst;

  const mutation = useMutation({
    mutationFn: async (body: { status?: string; analystNotes?: string }) => {
      const res = await apiRequest("PATCH", `/api/agents/reports/${draft.id}`, body);
      return res.json();
    },
    onSuccess: (_data, variables) => {
      setEditingNotes(false);
      const toastTitles: Record<string, string> = {
        approved: "Report approved",
        rejected: "Report rejected",
        qa_review: "Sent for QA Review",
      };
      toast({
        title: variables.status ? (toastTitles[variables.status] ?? `Report ${variables.status}`) : "Notes saved",
      });
      queryClient.invalidateQueries({ queryKey: ["/api/agents/reports"] });
    },
    onError: (err: Error) => {
      toast({ title: "Update failed", description: err.message, variant: "destructive" });
    },
  });

  const pending = mutation.isPending;
  const content = draft.content;
  const createdAt = draft.createdAt ? new Date(draft.createdAt) : null;
  const hoursAgo = createdAt
    ? Math.round((Date.now() - createdAt.getTime()) / 3600000)
    : null;

  return (
    <Card className="border-white/10 bg-card/50 backdrop-blur-sm">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <FileText className="h-5 w-5 shrink-0 text-primary" />
            <div>
              <CardTitle className="text-base">
                Week {draft.weekNumber ?? "?"} Report
                <span className="ml-2 text-sm font-normal text-muted-foreground capitalize">
                  — {draft.reportType ?? "weekly"}
                </span>
              </CardTitle>
              {hoursAgo !== null && (
                <p className="mt-0.5 flex items-center gap-1 text-xs text-muted-foreground">
                  <Clock className="h-3 w-3" />
                  Generated {hoursAgo < 1 ? "just now" : `${hoursAgo}h ago`} by A10
                </p>
              )}
            </div>
          </div>
          <Badge className={cn("shrink-0", statusMeta.className)}>{statusMeta.label}</Badge>
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* Quick stats row */}
        {content && (
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
            {content.trafficSnapshot && (
              <>
                <StatChip label="Sessions" value={content.trafficSnapshot.sessions.toLocaleString()} />
                <StatChip label="Users" value={content.trafficSnapshot.users.toLocaleString()} />
                <StatChip label="Conversions" value={content.trafficSnapshot.conversions.toLocaleString()} />
              </>
            )}
            {content.anomaliesSection && (
              <StatChip
                label="Anomalies"
                value={`${content.anomaliesSection.count} (${content.anomaliesSection.p0Count} P0)`}
                alert={content.anomaliesSection.p0Count > 0}
              />
            )}
          </div>
        )}

        {/* Expandable executive summary preview */}
        {content?.executiveSummary && content.executiveSummary.length > 0 && (
          <div>
            <button
              type="button"
              className="flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-foreground"
              onClick={() => setExpanded((v) => !v)}
            >
              {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
              Executive Summary Preview
            </button>
            {expanded && (
              <ul className="mt-2 space-y-1 pl-4">
                {content.executiveSummary.map((bullet, i) => (
                  <li key={i} className="text-sm text-muted-foreground">
                    • {bullet}
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}

        {/* Analyst notes */}
        <div>
          {editingNotes ? (
            <div className="space-y-2">
              <Textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="Add analyst notes..."
                rows={3}
                className="text-sm"
              />
              <div className="flex gap-2">
                <Button
                  size="sm"
                  variant="default"
                  disabled={pending}
                  onClick={() => mutation.mutate({ analystNotes: notes })}
                >
                  {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                  Save Notes
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  disabled={pending}
                  onClick={() => {
                    setNotes(draft.analystNotes ?? "");
                    setEditingNotes(false);
                  }}
                >
                  Cancel
                </Button>
              </div>
            </div>
          ) : (
            <div className="flex items-start gap-2">
              {draft.analystNotes ? (
                <p className="flex-1 text-sm italic text-muted-foreground">{draft.analystNotes}</p>
              ) : (
                <p className="flex-1 text-xs text-muted-foreground/50">No analyst notes yet.</p>
              )}
              <Button
                size="sm"
                variant="ghost"
                className="shrink-0"
                onClick={() => setEditingNotes(true)}
              >
                <Edit3 className="h-3.5 w-3.5" />
                {draft.analystNotes ? "Edit Notes" : "Add Notes"}
              </Button>
            </div>
          )}
        </div>

        {/* QA result panel */}
        {qaResult && (
          <div className={cn(
            "rounded-md border p-3 space-y-2",
            qaResult.passed
              ? "border-green-500/30 bg-green-500/5"
              : "border-red-500/30 bg-red-500/5",
          )}>
            <div className="flex items-center gap-2">
              {qaResult.passed ? (
                <ShieldCheck className="h-4 w-4 text-green-400" />
              ) : (
                <ShieldAlert className="h-4 w-4 text-red-400" />
              )}
              <span className={cn("text-sm font-medium", qaResult.passed ? "text-green-400" : "text-red-400")}>
                {qaResult.passed ? "QA Passed — Ready for approval" : "QA Failed — Issues found"}
              </span>
            </div>
            {!qaResult.passed && qaResult.issues.length > 0 && (
              <ul className="space-y-1 pl-6">
                {qaResult.issues.map((issue, i) => (
                  <li key={i} className="text-xs text-red-300">• {issue}</li>
                ))}
              </ul>
            )}
          </div>
        )}

        {/* Action buttons */}
        <div className="flex flex-wrap gap-2 border-t border-white/5 pt-3">
          <Button
            size="sm"
            variant="default"
            disabled={pending || draft.status === "approved" || draft.status === "delivered"}
            onClick={() => mutation.mutate({ status: "approved" })}
          >
            {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle className="h-4 w-4" />}
            Approve
          </Button>
          <Button
            size="sm"
            variant="ghost"
            disabled={pending || draft.status === "rejected"}
            onClick={() => mutation.mutate({ status: "rejected" })}
          >
            <XCircle className="h-4 w-4" />
            Reject
          </Button>
          <Button
            size="sm"
            variant="outline"
            disabled={emailRunning || pending}
            onClick={async () => {
              setEmailRunning(true);
              try {
                const res = await fetch("/api/agents/communication/run", {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({ tenantId: draft.tenantId, reportDraftId: draft.id }),
                });
                if (!res.ok) {
                  const err = await res.json().catch(() => ({}));
                  throw new Error((err as { error?: string }).error ?? "Failed");
                }
                toast({ title: "Cover email drafted", description: "Review it below the report card." });
                qc.invalidateQueries({ queryKey: ["/api/agents/communication", draft.id] });
              } catch (err) {
                toast({ title: "Email draft failed", description: err instanceof Error ? err.message : String(err), variant: "destructive" });
              } finally {
                setEmailRunning(false);
              }
            }}
          >
            {emailRunning ? <Loader2 className="h-4 w-4 animate-spin" /> : <Mail className="h-4 w-4" />}
            {emailRunning ? "Drafting…" : "Draft Cover Email"}
          </Button>
          <Button
            size="sm"
            variant="outline"
            disabled={qaRunning || pending}
            onClick={async () => {
              setQaRunning(true);
              setQaResult(null);
              try {
                const res = await fetch("/api/agents/qa/run", {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({ tenantId: draft.tenantId, reportDraftId: draft.id }),
                });
                const data: QAResponse = await res.json();
                if (!res.ok) throw new Error((data as { error?: string }).error ?? "QA failed");
                setQaResult(data);
                toast({
                  title: data.passed ? "QA Passed" : "QA Failed",
                  description: data.passed
                    ? "Report is ready for analyst approval."
                    : `${data.issues.length} issue(s) found — see details below.`,
                  variant: data.passed ? "default" : "destructive",
                });
                queryClient.invalidateQueries({ queryKey: ["/api/agents/reports"] });
              } catch (err) {
                toast({ title: "QA error", description: err instanceof Error ? err.message : String(err), variant: "destructive" });
              } finally {
                setQaRunning(false);
              }
            }}
          >
            {qaRunning ? <Loader2 className="h-4 w-4 animate-spin" /> : <FlaskConical className="h-4 w-4" />}
            {qaRunning ? "Running QA…" : "Request QA Review"}
          </Button>
        </div>

        {/* Email drafts — rendered below action buttons, inside the card */}
        {emailDrafts.length > 0 && (
          <div className="space-y-3 border-t border-white/5 pt-3">
            {emailDrafts.map((ed) => (
              <EmailDraftCard
                key={ed.id}
                emailDraft={ed}
                onUpdated={() => qc.invalidateQueries({ queryKey: ["/api/agents/communication", draft.id] })}
              />
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function StatChip({ label, value, alert }: { label: string; value: string; alert?: boolean }) {
  return (
    <div className={cn("rounded-md border border-white/5 bg-muted/30 px-3 py-2", alert && "border-red-500/30 bg-red-500/5")}>
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className={cn("text-sm font-semibold tabular-nums", alert && "text-red-400")}>{value}</p>
    </div>
  );
}

export default function ReviewQueuePage() {
  const { toast } = useToast();
  const { ga4PropertyId } = useDomain();
  const [running, setRunning] = useState(false);

  const { data: drafts = [], isLoading } = useQuery<ReportDraft[]>({
    queryKey: ["/api/agents/reports", ga4PropertyId],
    queryFn: async () => {
      if (!ga4PropertyId) return [];
      const res = await fetch(`/api/agents/reports?tenantId=${encodeURIComponent(ga4PropertyId)}`);
      if (!res.ok) throw new Error(await res.text());
      return res.json();
    },
    enabled: !!ga4PropertyId,
    refetchInterval: 30_000,
  });

  async function handleRunComposition() {
    if (!ga4PropertyId) return;
    setRunning(true);
    try {
      const res = await fetch("/api/agents/report/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tenantId: ga4PropertyId }),
      });
      if (!res.ok) throw new Error(await res.text());
      toast({ title: "Report composition started", description: "Draft will appear here when ready." });
      setTimeout(() => {
        queryClient.invalidateQueries({ queryKey: ["/api/agents/reports"] });
        setRunning(false);
      }, 5000);
    } catch (err) {
      toast({ title: "Failed to start", description: err instanceof Error ? err.message : String(err), variant: "destructive" });
      setRunning(false);
    }
  }

  const pendingCount = drafts.filter((d) => d.status === "pending_analyst").length;

  return (
    <div className="min-h-screen bg-background p-6">
      <div className="mx-auto max-w-4xl space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-foreground">Review Queue</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              AI-generated weekly reports awaiting analyst approval
            </p>
          </div>
          <div className="flex items-center gap-3">
            {pendingCount > 0 && (
              <Badge className="border-transparent bg-amber-500/15 text-amber-400">
                {pendingCount} pending
              </Badge>
            )}
            <Button
              variant="outline"
              size="sm"
              disabled={running || !ga4PropertyId}
              onClick={handleRunComposition}
            >
              {running ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <PlayCircle className="h-4 w-4" />
              )}
              Generate Report
            </Button>
          </div>
        </div>

        {/* Content */}
        {isLoading ? (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
          </div>
        ) : drafts.length === 0 ? (
          <Card className="border-dashed border-white/10 bg-card/30">
            <CardContent className="flex flex-col items-center justify-center py-16 text-center">
              <AlertCircle className="mb-3 h-10 w-10 text-muted-foreground/40" />
              <p className="text-sm font-medium text-muted-foreground">No report drafts yet</p>
              <p className="mt-1 text-xs text-muted-foreground/60">
                Click "Generate Report" to run A10 and create the first draft.
              </p>
            </CardContent>
          </Card>
        ) : (
          <>
            <div className="space-y-4">
              {drafts.map((draft) => (
                <ReportDraftCard key={draft.id} draft={draft} />
              ))}
            </div>
            <p className="text-center text-xs text-muted-foreground/40">
              {drafts.length} report{drafts.length !== 1 ? "s" : ""} in queue
            </p>
          </>
        )}
      </div>
    </div>
  );
}
